language: python
cache: pip
sudo: required
services:
  - docker

# Upgrade to latest docker-engine
before_install:
  - sudo apt-get update -qq
  - sudo DEBIAN_FRONTEND=noninteractive apt-get install -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" docker-engine

install:
  - pip install -U docker-py

script:
    - BUILD="--release OMERO-DEV-latest" omero-grid/test.sh
